### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by OrangeIsALie** [pop-os/cosmic-greeter#62]
This happens about 90% of the time then randomly will just work - after starting my laptop with Cosmic installed, I see the login screen and enter my password, then afterwards the password entry box disappears but user is never logged in and it just sits there at the login screen. Everything is still clickable. There is just a user with avatar picture and no password entry box, but the other controls are still available. I can successfully restart from here but that's about it.

**Comment by OrangeIsALie** [comment]
> I'm assuming you're using cosmic-greeter?

Probably - I installed Cosmic using apt install cosmic-*

Thanks

**Comment by ids1024** [comment]
I saw this yesterday as well. Not sure if something has changed recently to cause this.

**Comment by tomszar** [comment]
The same happened to me today. Running Pop!_OS 22.04 and installed cosmic, including cosmic-greeter through `sudo apt install cosmic-session`

**Comment by OMGhixD-OG** [comment]
Happened to me as well last night. Decided to boot into the live environment and do the installation process in reverse. I then retried to log in again, and I was permitted to do so. I then uninstall all COSMIC related packages and rebooted. And yet again I am allowed to log in.

Glad this got reported. ^ there's the solution to recover your system. I tried TTY, but no button combo worked.

**Comment by LinuxBoy-96** [comment]
This need to be fix ASAP. I'm plaged big this issue since I use Cosmic. 
Everytime I try to log in there is a 50% chance the Windows Manager would stop to function.
Like the password field disapear and nothing happen.
It does not matter what session I choose.
My only fix is to reboot and try again.

**Comment by WatchMkr** [comment]
Should be resolved with today's updates.

**Comment by LinuxBoy-96** [comment]
> Should be resolved with today's updates.

It is absolutely NOT resolved....
Plz re-open the issue.

**Comment by mmstick** [comment]
@LinuxBoy-96 It was resolved. The ecryptfs package was causing PAM to break, which the update has removed.

**Comment by dharmik2319** [comment]
I can confirm it is not resolved yet.

**Comment by xvil** [comment]
I applied the latest updates and the problem remains.
I can log in just fine by switching to gdm3.
With Cosmic DE, it's not working.
I get the "pam_authenticate: AUTH_ERR" message.
As the "show password" little eye icon is not working, that's not easy to troubleshoot.

I am NOT using the US keyboard layout.
I tried typing the password as if the US layout was selected but it didn't work either.

When logging in from a terminal (ctrl+alt+f2 for example), the keyboard layout is correct though.

**Comment by Lostendalfah1980** [comment]
I'm having a similar issue. I'm on 24.04 Cosmic. I also did a `sudo apt update && sudo apt full-upgrade` 2 days ago, so I don't think that is my issue. I'm also not seeing any error when I go to login.

What does happen is I input in my password, it goes to a terminal screen, runs through some code and then finishes on trying to run something via bash, hangs for half a second, then comes back to the login screen. I installed zsh and oh-my-zsh, including putting it into my $PATH. I suspect that something broke that needs bash to run (a) script(s) and is probably my issue.

What I need help with: I'm okay at navigating Linux and so I just need to be pointed to how to gather information to troubleshoot the issue. I can google-fu or come back here if I can't figure it out.

Could someone point me in the right direction, please?
